version: '0.2'

phases:
  install:
    commands:
      - echo "instalando dependencias ..." 
      - npm install
  pre_build:
    commands:
      - echo "ejecuntando pruebas ..."  
      - npm test
  build:
    commands:
      - echo "construncción ejecutandose ..."  
      - zip -r code.zip ."  
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
    - code.zip
  discard-paths: yes
